version: '3.8'
services:
  video-service:
    build:
      context: .
      dockerfile: Dockerfile.video
    env_file:
      - .env
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    networks:
      - app_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  search-service:
    build:
      context: .
      dockerfile: Dockerfile.search
    env_file:
      - .env
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    depends_on:
      - elasticsearch
    networks:
      - app_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile.payment
    env_file:
      - .env
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    networks:
      - app_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  redis:
    image: redis:latest
    networks:
      - app_network

  elasticsearch:
    image: elasticsearch:7.17.9
    environment:
      - discovery.type=single-node
    networks:
      - app_network

  nginx:
    image: nginx:latest
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure
    networks:
      - app_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    command: celery -A core.celery_app worker --loglevel=info
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    networks:
      - app_network
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224

networks:
  app_network:
    driver: bridge
